VALIDATE_ALL_CODEBASE: false

GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
GITHUB_CHECK_RUN_REPORTER: true

ENABLE_LINTERS:
  # PHP
  - PHP_PHPSTAN
  - PHP_PHPCS

  # Vue / JS / TS
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES
  - VUE_ES

  # Python
  - PYTHON_FLAKE8

  # Web
  - HTML_HTMLHINT
  - CSS_STYLELINT

  # Dev / infra
  - DOCKERFILE_HADOLINT
  - MARKDOWN_MARKDOWNLINT
  - SQL_SQLFLUFF

DISABLE:
  - COPYPASTE
  - SPELL
  - REPOSITORY
