name: MegaLinter

on:
  pull_request:
    branches:
      - main
      - master

env:
  APPLY_FIXES: none
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Install reviewdog
      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/fd59714416d6d9a1c0692d872e38e7f8448df4fc/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v9
        id: ml
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: >-
            ${{
              github.event_name == 'push' &&
              github.ref == 'refs/heads/main'
            }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Convert MegaLinter reports to RDJSONL
      - name: Convert SARIF reports to rdjsonl
        if: always()
        run: |
          mkdir -p rdjsonl

          if [ -d "megalinter-reports" ]; then
            find megalinter-reports -name "*.sarif" | while read file; do
              tool=$(basename "$file" .sarif)
              reviewdog -f=sarif -name="$tool" -reporter=rdjsonl < "$file" >> rdjsonl/results.rdjsonl || true
            done
          fi

      # Run reviewdog to comment on PR
      - name: Run reviewdog
        if: always() && github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f rdjsonl/results.rdjsonl ]; then
            cat rdjsonl/results.rdjsonl | reviewdog \
              -f=rdjsonl \
              -name="megalinter" \
              -reporter=github-pr-review \
              -fail-on-error=false
          fi

      - name: Upload MegaLinter artifacts
        uses: actions/upload-artifact@v7
        if: success() || failure()
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log

      - name: Fail job if MegaLinter failed
        if: steps.ml.outcome == 'failure'
        run: exit 1
