name: Reviewdog

on:
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: reviewdog/action-setup@v1.3.0
        with:
          # reviewdog version. [latest,nightly,vX.Y.Z]
          reviewdog_version: # optional, default is latest

      - name: misspell
        id: misspell
        uses: reviewdog/action-misspell@9daa94af4357dddb6fd3775de806bc0a8e98d3e4 # v1.26.3
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"

      - uses: dciborow/action-pylint@0.1.0
        continue-on-error: true
        id: pylint
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-check
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
          glob_pattern: "**/*.py"

      - name: Fail if reviewdog found issues
        if: steps.misspell.outcome == 'failure' || steps.pylint.outcome == 'failure'
        run: exit 1
