name: Reviewdog

on:
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      - name: misspell
        uses: reviewdog/action-misspell@9daa94af4357dddb6fd3775de806bc0a8e98d3e4 # v1.26.3
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"

      - uses: dciborow/action-pylint@0.1.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning
          glob_pattern: "**/*.py"

      # - name: Run reviewdog
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     reviewdog -reporter=github-pr-check -runners=golint,govet
      #     # or
      #     reviewdog -reporter=github-pr-review -runners=golint,govet
